
std-install: graphics


pre:
	sudo apt-get update
	sudo apt-get install openssh-server
	sudo apt-get install git

graphics:
	sudo apt-get install gthumb

python3:
	sudo apt-get -y install python3-dev
	sudo apt-get -y install gfortran
	sudo apt-get -y install libopenblas-dev
	sudo apt-get -y install liblapack-dev
	sudo apt-get -y install graphviz
	sudo apt-get -y install python3-pip

