all: sphinx

sphinx:
	echo install sphinx
	sudo apt update && sudo apt install python3-pip
	sudo apt-get install python-sphinx

add:
	pip3 install recommonmark
	pip3 install sphinx_rtd_theme


dc:
	./installDocker.sh

